# this is a level 1 header

In [1]:
# This is a comment

In [2]:
import numpy as np

In [3]:
## making a list

list_1 = [1, 2, 3]

In [4]:
# making the list into a vector
vec_1 = np.array(list_1)

In [5]:
vec_1

array([1, 2, 3])

In [6]:
# making a second list, then vector using np.array, for math stuff!

list_2 = [10, 100, 1000]

vec_2 = np.array(list_2)

vec_2

array([  10,  100, 1000])

In [7]:
# baby math w vectors

# addition
vec_1 + vec_2

# subtraction
vec_1 - vec_2

array([  -9,  -98, -997])

In [8]:
# scalar multiplier

5 * vec_2

array([  50,  500, 5000])

notes from class instructions: "BEWARE: If you do these operations with the original lists, something very different will happen, since the + with lists appends the second list elements to the first list."


In [9]:
# example of trying addition with lists, not vectors

list_1 + list_2

[1, 2, 3, 10, 100, 1000]

for dot product, use np.dot()

In [10]:
# this is a change

In [11]:
# Make one 2 x 2 matrix: 
matrix_1 = np.matrix([[1, 9], 
               [6, 0]])
print(matrix_1)

[[1 9]
 [6 0]]


In [12]:
matrix_2 = np.matrix([[0, 2],
                      [3, 10]])
                      
print(matrix_2)

[[ 0  2]
 [ 3 10]]
